/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author SOFIA ELIZONDO
 */
public class InformacionEstudiantes extends javax.swing.JPanel {

    /**
     * Creates new form InformacionEstudiantes
     */
    public InformacionEstudiantes() {
        initComponents();
    }
    
    public String[] devolverInformacion()
    {
        String arreglo[];
        arreglo=new String[3];
        arreglo[0]=this.jt_Cedula.getText();
        arreglo[1]=this.jt_Nombre.getText();
        arreglo[2]=this.jt_Direccion.getText();
        
        return arreglo;
    }
    public String devolverCedula()
    {
        return this.jt_Cedula.getText();
    }
    public void mostrarInformacion(String arreglo[])
    {
        this.jt_Nombre.setText(arreglo[0]);
        this.jt_Direccion.setText(arreglo[1]);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jt_Cedula = new javax.swing.JTextField();
        jt_Nombre = new javax.swing.JTextField();
        jt_Direccion = new javax.swing.JTextField();
        jl_Cedula = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_DIreccion = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);
        add(jt_Cedula);
        jt_Cedula.setBounds(120, 20, 102, 20);
        add(jt_Nombre);
        jt_Nombre.setBounds(120, 50, 102, 20);
        add(jt_Direccion);
        jt_Direccion.setBounds(120, 90, 102, 20);

        jl_Cedula.setText("Cédula");
        add(jl_Cedula);
        jl_Cedula.setBounds(23, 26, 60, 14);

        jl_Nombre.setText("Nombre");
        add(jl_Nombre);
        jl_Nombre.setBounds(23, 57, 70, 14);

        jl_DIreccion.setText("Dirección");
        add(jl_DIreccion);
        jl_DIreccion.setBounds(23, 88, 70, 14);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_DIreccion;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Direccion;
    private javax.swing.JTextField jt_Nombre;
    // End of variables declaration//GEN-END:variables
}
