/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ControladorEstudiantes;
import javax.swing.JOptionPane;

/**
 *
 * @author SOFIA ELIZONDO
 */
public class RegistroEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form RegistroEstudiantes
     */
    
    ControladorEstudiantes controlador;
    public RegistroEstudiantes() {
        initComponents();
        this.setLocation(500, 300);
        setVisible(false);
        controlador=new ControladorEstudiantes(this);
        botones2.agregarEventos(controlador);
        estadoInicial();
        
    }
    
    public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    
    public void habilitarAgregar()
    {
        this.botones2.habilitarAgregar();
        this.informacionEstudiantes1.habilitarAgregar();
    }

    public void estadoInicial()
    {
        this.botones2.estadoInicial();
        this.informacionEstudiantes1.blanquear();
        this.informacionEstudiantes1.estadoInicial();
    }
    
    public void habilitarModificar()
    {
        this.botones2.habilitarModificar();
        this.informacionEstudiantes1.habilitarModificar();
    }
    
    
    public String[] devolverInformacion()
    {
        return informacionEstudiantes1.devolverInformacion();
    }
    public String devolverCedula()
    {
        return informacionEstudiantes1.devolverCedula();
    }
    public void mostrarInformacion(String arreglo[])
    {
        informacionEstudiantes1.mostrarInformacion(arreglo);
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        botones2 = new Vista.Botones();
        Girasol = new javax.swing.JLabel();
        informacionEstudiantes1 = new Vista.InformacionEstudiantes();
        FondoBlanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(615, 490));
        getContentPane().setLayout(null);

        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PracticaLab01/Of.Registro.png"))); // NOI18N
        getContentPane().add(Titulo);
        Titulo.setBounds(20, 10, 540, 140);
        getContentPane().add(botones2);
        botones2.setBounds(20, 310, 590, 140);

        Girasol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PracticaLab01/GirasolUCR.png"))); // NOI18N
        getContentPane().add(Girasol);
        Girasol.setBounds(390, 0, 236, 472);
        getContentPane().add(informacionEstudiantes1);
        informacionEstudiantes1.setBounds(100, 140, 280, 160);

        FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PracticaLab01/FondoBlanco.png"))); // NOI18N
        getContentPane().add(FondoBlanco);
        FondoBlanco.setBounds(0, 0, 620, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel Girasol;
    private javax.swing.JLabel Titulo;
    private Vista.Botones botones2;
    private Vista.InformacionEstudiantes informacionEstudiantes1;
    // End of variables declaration//GEN-END:variables
}
